### ISSUE TITLE
Name Error Reload

### ISSUE THREAD

**Issue by olpossum** [olpossum/sodogetip#4]
When running main.py

`Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from dogetipper import SoDogeTip
  File "C:\Users\Andy\Google Drive\Python\RedditBots\TipBots\LTC\sodogetip\dogetipper.py", line 8, in <module>
    import bot_command
  File "C:\Users\Andy\Google Drive\Python\RedditBots\TipBots\LTC\sodogetip\bot_command.py", line 11, in <module>
    import lang
  File "C:\Users\Andy\Google Drive\Python\RedditBots\TipBots\LTC\sodogetip\lang.py", line 5, in <module>
    reload(sys)
NameError: name 'reload' is not defined`

 Using python 3.6.1

**Comment by olpossum** [comment]
removed the call to reload along with changes in #5
