### ISSUE TITLE
module 'sys' has no attribute 'setdefaultencoding'

### ISSUE THREAD

**Issue by olpossum** [olpossum/sodogetip#5]
when running main.py

`Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from dogetipper import SoDogeTip
  File "C:\Users\Andy\Google Drive\Python\RedditBots\TipBots\LTC\sodogetip\dogetipper.py", line 8, in <module>
    import bot_command
  File "C:\Users\Andy\Google Drive\Python\RedditBots\TipBots\LTC\sodogetip\bot_command.py", line 11, in <module>
    import lang
  File "C:\Users\Andy\Google Drive\Python\RedditBots\TipBots\LTC\sodogetip\lang.py", line 6, in <module>
    sys.setdefaultencoding("utf-8")
AttributeError: module 'sys' has no attribute 'setdefaultencoding'`

Using python 3.6.1

**Comment by olpossum** [comment]
Warnings against this here: https://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

**Comment by olpossum** [comment]
This is a no-op in python 3+ and UTF-8 is the default encoding. This can be removed.
